import type { Product, TraceabilityStep } from '@/types/product';

// ============================================================
// Featured Products (Landing Page)
// ============================================================
export const FEATURED_PRODUCTS: Product[] = [
  {
    id: 'fp-001',
    slug: 'gula-cair-nipah',
    name: 'Gula Cair Nipah Organik',
    description: 'Pemanis cair alami dari nira nipah pesisir dengan indeks glikemik rendah.',
    price: 45000,
    currency: 'IDR',
    imageUrl: '/images/products/gula-cair-nipah.webp',
    imageAlt: 'Gula cair nipah organik dalam kemasan',
    badge: { label: 'Eco-Certified', variant: 'eco' },
    category: 'Pemanis',
    seller: 'Koperasi Nelayan Aceh',
    isVerified: true,
  },
  {
    id: 'fp-002',
    slug: 'kertas-pelepah-nipah',
    name: 'Kertas Daur Ulang Pelepah',
    description: 'Kertas estetik yang dibuat dari limbah pelepah nipah, cocok untuk kerajinan.',
    price: 35000,
    currency: 'IDR',
    imageUrl: '/images/products/kertas-nipah.webp',
    imageAlt: 'Kertas daur ulang dari serat pelepah nipah',
    badge: { label: 'Handmade', variant: 'handmade' },
    category: 'Kerajinan',
    seller: 'UMKM Karya Pesisir',
    isVerified: true,
  },
  {
    id: 'fp-003',
    slug: 'sirup-nipah-premium',
    name: 'Sirup Nipah Premium',
    description: 'Sirup manis alami dengan aroma khas nektar nipah yang kuat dan karamel.',
    price: 55000,
    currency: 'IDR',
    imageUrl: '/images/products/sirup-nipah.webp',
    imageAlt: 'Sirup nipah premium dalam kemasan botol kaca',
    category: 'Minuman',
    seller: 'Aceh Artisanal Syrup',
    isVerified: true,
  },
];

// ============================================================
// Marketplace Products
// ============================================================
export const MARKETPLACE_PRODUCTS: Product[] = [
  {
    id: 'mp-001',
    slug: 'gula-semut-nipah',
    name: 'Gula Semut Nipah',
    description: 'Gula kristal 100% alami hasil proses tradisional masyarakat Aceh.',
    price: 35000,
    currency: 'IDR',
    imageUrl: '/images/products/gula-semut-nipah.webp',
    imageAlt: 'Gula semut kristal nipah',
    badge: { label: 'Verified Seller', variant: 'verified' },
    category: 'Pemanis',
    seller: 'Mitra Tani Aceh Barat',
    isVerified: true,
  },
  {
    id: 'mp-002',
    slug: 'cuka-nipah-tradisional',
    name: 'Cuka Nipah Tradisional',
    description: 'Cuka fermentasi nira nipah murni, baik untuk pencernaan dan masakan khas.',
    price: 25000,
    currency: 'IDR',
    imageUrl: '/images/products/cuka-nipah.webp',
    imageAlt: 'Cuka nipah dalam botol kaca',
    badge: { label: 'Verified Seller', variant: 'verified' },
    category: 'Bumbu',
    seller: 'UMKM Cuka Pesisir',
    isVerified: true,
  },
  {
    id: 'mp-003',
    slug: 'manisan-nipah',
    name: 'Manisan (Meuseukat) Nipah',
    description: 'Kue tradisional khas Aceh yang dibuat dengan nira nipah murni tanpa pengawet.',
    price: 45000,
    currency: 'IDR',
    imageUrl: '/images/products/manisan-nipah.webp',
    imageAlt: 'Manisan dan meuseukat nipah',
    category: 'Makanan',
    seller: 'Warisan Nenek Kitchen',
    isVerified: true,
  },
  {
    id: 'mp-004',
    slug: 'sabun-cair-nipah',
    name: 'Sabun Cair Ekstrak Nipah',
    description: 'Sabun cair natural dengan ekstrak daun nipah yang kaya akan antioksidan.',
    price: 28000,
    currency: 'IDR',
    imageUrl: '/images/products/sabun-cair-nipah.webp',
    imageAlt: 'Botol sabun cair dari ekstrak nipah',
    badge: { label: 'Verified Seller', variant: 'verified' },
    category: 'Perawatan Diri',
    seller: 'EcoNipah Labs',
    isVerified: true,
  },
  {
    id: 'mp-005',
    slug: 'briket-arang-nipah',
    name: 'Briket Arang Nipah',
    description: 'Briket arang dari sisa pelepah nipah, ramah lingkungan dan tahan lama.',
    price: 15000,
    currency: 'IDR',
    imageUrl: '/images/products/arang-nipah.webp',
    imageAlt: 'Tumpukan briket arang nipah',
    category: 'Energi',
    seller: 'Koperasi Energi Hijau',
    isVerified: false,
  },
  {
    id: 'mp-006',
    slug: 'serat-pelepah-nipah',
    name: 'Serat Pelepah Nipah',
    description: 'Bahan baku serat nipah berkualitas tinggi untuk kerajinan anyaman.',
    price: 20000,
    currency: 'IDR',
    imageUrl: '/images/products/serat-pelepah.webp',
    imageAlt: 'Serat pelepah nipah yang sudah dikeringkan',
    badge: { label: 'Verified Seller', variant: 'verified' },
    category: 'Bahan Baku',
    seller: 'Komunitas Penganyam Aceh',
    isVerified: true,
  },
];

// ============================================================
// Product Detail - Traceability Steps
// ============================================================
export const TRACEABILITY_STEPS: TraceabilityStep[] = [
  {
    id: 'step-farmer',
    icon: 'agriculture',
    title: 'The Farmer',
    subtitle: 'Ujong Batee Mangrove Community',
    description: 'Sustainable harvesting of palm leaves that supports local ecosystem preservation.',
    metadata: 'Batch #NP-2024-08',
  },
  {
    id: 'step-msme',
    icon: 'precision_manufacturing',
    title: 'The MSME',
    subtitle: 'Rumoh Anyaman Aceh',
    description: 'Artisan collective where materials are processed and woven into refined goods.',
    metadata: 'Artisan ID: AT-142',
  },
  {
    id: 'step-product',
    icon: 'shopping_bag',
    title: 'The Product',
    subtitle: 'NipaHub Premium Collection',
    description: 'Quality assured and ready for global shipping to your doorstep.',
    metadata: 'Shipped from: Banda Aceh',
  },
];
